### ISSUE TITLE
Improve implementation for different model types

### ISSUE THREAD

**Issue by ybracke** [ybracke/transnormer#67]
It is allowed to use either a byte-based encoder-decoder as base model **or** a two BPE-based models (encoder and decoder). 
However, the implementation is still a bit awkward with multiple `if/else`-structures, concerning (1) the choice of the tokenizer and transliterator (see [here](https://github.com/ybracke/transnormer/blob/23a52b68bc67035e06a90afbeb0f5296618322ea/src/transnormer/models/train_model.py#L71C2-L71C2)), (2) the choice of the model class and loading function (see [here](https://github.com/ybracke/transnormer/blob/23a52b68bc67035e06a90afbeb0f5296618322ea/src/transnormer/models/train_model.py#L174)) and the correct special tokens (see [here](https://github.com/ybracke/transnormer/blob/23a52b68bc67035e06a90afbeb0f5296618322ea/src/transnormer/models/train_model.py#L186)).

Update the implementation. Perhaps use an [abstract base class](https://python-course.eu/oop/the-abc-of-abstract-base-classes.php) for the models with a `load` function that is defined in the subclasses for `T5ForConditionalGeneration`, `EncoderDecoderModel` and perhaps others.

**Comment by ybracke** [comment]
Idea for an update to the train configs (here in yaml instead of toml): 

```yaml
tokenizer:
    from-model: true|false 
    path: str # only if from-model == false    
    input-transliterator: str # optional
language models:
    model-type: str # must be one of {T5, separate, ...}
    encoder: # only if model-type in {separate, ...}
        checkpoint: str
    decoder: # only if model-type in {separate, ...}
        checkpoint: str   
    encoder-decoder: # only if model-type in {T5, ...}
        checkpoint: str   
```
